export const FILMS = [
  {
    id: 1,
    title: 'Capitão América: O Primeiro Vingador',
    releaseYear: 2011,
    country: 'Estados Unidos',
    director: 'Joe Johnston',
    image: './films/captainamericafirstavenger.jpg',
  },
  {
    id: 2,
    title: 'Capitã Marvel',
    releaseYear: 2019,
    country: 'Estados Unidos',
    director: 'Anna Boden e Ryan Fleck',
    image: './films/captainmarvel.jpg',
  },
  {
    id: 3,
    title: 'O Incrível Hulk',
    releaseYear: 2008,
    country: 'Estados Unidos',
    director: 'Louis Leterrier',
    image: './films/theincrediblehulk.jpg',
  },
  {
    id: 4,
    title: 'Homem de Ferro',
    releaseYear: 2008,
    country: 'Estados Unidos',
    director: 'Jon Favreau',
    image: './films/ironman1.jpg',
  },
  {
    id: 5,
    title: 'Homem de Ferro 2',
    releaseYear: 2010,
    country: 'Estados Unidos',
    director: 'Jon Favreau',
    image: './films/ironman2.jpg',
  },
  {
    id: 6,
    title: 'Thor',
    releaseYear: 2011,
    country: 'Estados Unidos',
    director: 'Taika Waititi, Alan Taylor e Kenneth Branagh',
    image: './films/thor.jpg',
  },
  {
    id: 7,
    title: 'Os Vingadores',
    releaseYear: 2012,
    country: 'Estados Unidos',
    director: 'Anthony Russo, Joss Whedon e Joe Russo',
    image: './films/avengers.jpg',
  },
  {
    id: 8,
    title: 'Homem de Ferro 3',
    releaseYear: 2013,
    country: 'Estados Unidos',
    director: 'Shane Black',
    image: './films/ironman3.jpg',
  },
  {
    id: 9,
    title: 'Thor: O Mundo Sombrio',
    releaseYear: 2013,
    country: 'Estados Unidos',
    director: 'Alan Taylor',
    image: './films/thorthedarkworld.jpg',
  },
  {
    id: 10,
    title: 'Capitão América: O Soldado Invernal',
    releaseYear: 2014,
    country: 'Estados Unidos',
    director: 'Anthony Russo e Joe Russo',
    image: './films/captainamericathewintersoldier.jpg',
  },
  {
    id: 11,
    title: 'Guardiões da Galáxia',
    releaseYear: 2014,
    country: 'Estados Unidos',
    director: 'James Gunn',
    image: './films/guardiansofthegalaxy.jpg',
  },
  {
    id: 12,
    title: 'Guardiões da Galáxia Vol. 2',
    releaseYear: 2017,
    country: 'Estados Unidos',
    director: 'James Gunn',
    image: './films/guardiansofthegalaxyvol2.jpg',
  },
  {
    id: 13,
    title: 'Vingadores: Era de Ultron',
    releaseYear: 2015,
    country: 'Estados Unidos',
    director: 'Joss Whedon',
    image: './films/avengersageofultron.jpg',
  },
  {
    id: 14,
    title: 'Homem-Formiga',
    releaseYear: 2015,
    country: 'Estados Unidos',
    director: 'Peyton Reed',
    image: './films/antman.jpg',
  },
  {
    id: 15,
    title: 'Capitão América: Guerra Civil',
    releaseYear: 2016,
    country: 'Estados Unidos',
    director: 'Anthony Russo e Joe Russo',
    image: './films/captainamericacivilwar.jpg',
  },
  {
    id: 16,
    title: 'Pantera Negra',
    releaseYear: 2018,
    country: 'Estados Unidos',
    director: 'Ryan Coogler',
    image: './films/blackpanther.jpg',
  },
  {
    id: 17,
    title: 'Homem-Aranha: De Volta ao Lar',
    releaseYear: 2017,
    country: 'Estados Unidos',
    director: 'Jon Watts',
    image: './films/spidermanhomecoming.jpg',
  },
  {
    id: 18,
    title: 'Viúva Negra',
    releaseYear: 2021,
    country: 'Estados Unidos',
    director: 'Cate Shortland',
    image: './films/blackwidow.jpg',
  },
  {
    id: 19,
    title: 'Doutor Estranho',
    releaseYear: 2016,
    country: 'Estados Unidos',
    director: 'Scott Derrickson',
    image: './films/doctorstrange.jpg',
  },
  {
    id: 20,
    title: 'Thor: Ragnarok',
    releaseYear: 2017,
    country: 'Estados Unidos',
    director: 'Taika Waititi',
    image: './films/thorragnarok.jpg',
  },
  {
    id: 21,
    title: 'Vingadores: Guerra Infinita',
    releaseYear: 2018,
    country: 'Estados Unidos',
    director: 'Anthony Russo e Joe Russo',
    image: './films/avengersinfinitywar.jpg',
  },
  {
    id: 22,
    title: 'Homem-Formiga e a Vespa',
    releaseYear: 2018,
    country: 'Estados Unidos',
    director: 'Peyton Reed',
    image: './films/antmanandwasp.jpg',
  },
  {
    id: 23,
    title: 'Vingadores: Ultimato',
    releaseYear: 2019,
    country: 'Estados Unidos',
    director: 'Anthony Russo e Joe Russo',
    image: './films/avengersendgame.jpg',
  },
  {
    id: 24,
    title: 'Shang-Chi e a Lenda dos Dez Anéis',
    releaseYear: 2021,
    country: 'Estados Unidos',
    director: 'Destin Daniel Cretton',
    image: './films/shangchiethelegendofthesevenrings.jpg',
  },
  {
    id: 25,
    title: 'Eternos',
    releaseYear: 2021,
    country: 'Estados Unidos',
    director: 'Chloé Zhao',
    image: './films/eternal.jpg',
  },
  {
    id: 26,
    title: 'Homem-Aranha: Longe de Casa',
    releaseYear: 2019,
    country: 'Estados Unidos',
    director: 'Jon Watts',
    image: './films/spidermanfarfromhome.jpg',
  },
  {
    id: 27,
    title: 'Homem-Aranha: Sem Volta para Casa',
    releaseYear: 2021,
    country: 'Estados Unidos',
    director: 'Jon Watts',
    image: './films/spidermanwithouthomecoming.jpg',
  },
  {
    id: 28,
    title: 'Doutor Estranho no Multiverso da Loucura',
    releaseYear: 2022,
    country: 'Estados Unidos',
    director: 'Sam Raimi',
    image: './films/doctorstrangeinthemultiverseofmadness.jpg',
  },
  {
    id: 29,
    title: 'Thor: Amor e Trovão',
    releaseYear: 2022,
    country: 'Estados Unidos',
    director: 'Taika Waititi',
    image: './films/thorloveandthunder.jpg',
  },
  {
    id: 30,
    title: 'Pantera Negra - Wakanda Forever',
    releaseYear: 2022,
    country: 'Estados Unidos',
    director: 'Ryan Coogler',
    image: './films/blackpanthergrawakandaforever.jpg',
  },
];
